// Anthropic Claude Models Configuration
export const ANTHROPIC_MODELS = [
    {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet',
        provider: 'anthropic',
        apiKeyEnv: 'ANTHROPIC_API_KEY',
        apiKeyEnvAlt: 'CLAUDE_API_KEY',
        icon: null,
        description: 'Claude 3.5 Sonnet is Anthropic\'s most capable model with text and image understanding.',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 200000,
        maxTokens: 4096,
        live: false,
        url: 'https://anthropic.com/models/claude-3-5-sonnet-20241022',
    },
    {
        id: 'claude-sonnet-4-20250514',
        name: 'Claude Sonnet 4',
        provider: 'anthropic',
        apiKeyEnv: 'ANTHROPIC_API_KEY',
        apiKeyEnvAlt: 'CLAUDE_API_KEY',
        icon: null,
        description: 'Claude Sonnet 4 is Anthropic\'s most capable model with text and image understanding.',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 200000,
        maxTokens: 4096,
        live: false,
        url: 'https://anthropic.com/models/claude-sonnet-4-20250514',
    },
    {
        id: 'claude-opus-4-20250514',
        name: 'Claude Opus 4',
        provider: 'anthropic',
        apiKeyEnv: 'ANTHROPIC_API_KEY',
        apiKeyEnvAlt: 'CLAUDE_API_KEY',
        icon: null,
        badge: 'Premium',
        description: 'Claude Opus 4 is Anthropic\'s most capable model with text and image understanding.',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 200000,
        maxTokens: 4096,
        premium: true,
        live: false,
        url: 'https://anthropic.com/models/claude-opus-4-20250514',
    },
    {
        id: 'claude-4-sonnet',
        name: 'Claude 4 Sonnet',
        provider: 'anthropic',
        apiKeyEnv: 'ANTHROPIC_API_KEY',
        apiKeyEnvAlt: 'CLAUDE_API_KEY',
        icon: null,
        description: 'Most capable Claude model for complex tasks',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 200000,
        maxTokens: 4096,
        live: false,
    },
    {
        id: 'claude-4-opus',
        name: 'Claude 4 Opus',
        provider: 'anthropic',
        apiKeyEnv: 'ANTHROPIC_API_KEY',
        apiKeyEnvAlt: 'CLAUDE_API_KEY',
        icon: null,
        badge: 'MAX Only',
        description: 'Premium Claude model with maximum capabilities',
        capabilities: ['text', 'vision', 'code', 'analysis'],
        contextWindow: 200000,
        maxTokens: 4096,
        premium: true,
        live: false,
    },
    {
        id: 'claude-3.5-sonnet',
        name: 'Claude 3.5 Sonnet',
        provider: 'anthropic',
        apiKeyEnv: 'ANTHROPIC_API_KEY',
        apiKeyEnvAlt: 'CLAUDE_API_KEY',
        icon: null,
        description: 'Fast and efficient Claude model',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 200000,
        maxTokens: 4096,
        live: false,
    },
];

export const ANTHROPIC_PROVIDER_CONFIG = {
    name: 'Anthropic Claude',
    baseUrl: 'https://api.anthropic.com',
    keyLabel: 'Anthropic API Key',
    envKeys: ['ANTHROPIC_API_KEY', 'CLAUDE_API_KEY'],
    signupUrl: 'https://console.anthropic.com',
};