// Google Gemini Models Configuration
export const GOOGLE_MODELS = [
    {
        id: 'gemini-2.5-pro',
        name: 'Gemini 2.5 Pro',
        provider: 'google',
        apiKeyEnv: 'GOOGLE_API_KEY',
        apiKeyEnvAlt: 'GEMINI_API_KEY',
        icon: null,
        description: 'Gemini 2.5 Pro Preview with enhanced capabilities.',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 1000000,
        maxTokens: 8192,
        live: false,
        url: 'https://gemini.google.com/models/gemini-2.5-pro-preview-05-06',
    },
    {
        id: 'gemini-2.5-flash',
        name: 'Gemini 2.5 Flash',
        provider: 'google',
        apiKeyEnv: 'GOOGLE_API_KEY',
        apiKeyEnvAlt: 'GEMINI_API_KEY',
        icon: null,
        description: 'Gemini 2.5 Flash is a fast, efficient model with text and image capabilities.',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 1000000,
        maxTokens: 8192,
        live: false,
        url: 'https://gemini.google.com/models/gemini-2.5-flash',
    },
    {
        id: 'gemini-2.5-flash-lite-preview-06-17',
        name: 'Gemini 2.5 Flash Lite Preview',
        provider: 'google',
        apiKeyEnv: 'GOOGLE_API_KEY',
        apiKeyEnvAlt: 'GEMINI_API_KEY',
        icon: null,
        badge: 'Preview',
        description: 'Lightweight Gemini model with text and image capabilities.',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 1000000,
        maxTokens: 8192,
        live: false,
        url: 'https://gemini.google.com/models/gemini-2.5-flash-lite-preview-06-17',
    },
    {
        id: 'gemini-2.0-flash-live-001',
        name: 'Gemini 2.0 Flash Live',
        provider: 'google',
        apiKeyEnv: 'GOOGLE_API_KEY',
        apiKeyEnvAlt: 'GEMINI_API_KEY',
        icon: null,
        badge: 'LIVE',
        description: 'Gemini 2.0 Flash Live 001 is a fast, efficient model with text and image capabilities.',
        capabilities: ['text', 'vision', 'code', 'audio', 'video', 'realtime'],
        contextWindow: 1000000,
        maxTokens: 8192,
        live: true,
        url: 'https://gemini.google.com/models/gemini-2.0-flash-live-001',
    },
];

export const GOOGLE_PROVIDER_CONFIG = {
    name: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com',
    keyLabel: 'Google API Key',
    envKeys: ['GOOGLE_API_KEY', 'GEMINI_API_KEY'],
    signupUrl: 'https://aistudio.google.com',
};