// OpenRouter Models Configuration
export const OPENROUTER_MODELS = [
    {
        id: 'anthropic/claude-3.5-sonnet',
        name: 'Claude 3.5 Sonnet (OpenRouter)',
        provider: 'openrouter',
        apiKeyEnv: 'OPENROUTER_API_KEY',
        icon: null,
        description: 'Claude 3.5 Sonnet via OpenRouter with text and image understanding.',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 200000,
        maxTokens: 4096,
        live: false,
        url: 'https://openrouter.ai/models/anthropic/claude-3.5-sonnet',
    },
    {
        id: 'deepseek/deepseek-chat-v3-0324:free',
        name: 'DeepSeek Chat V3 (OpenRouter)',
        provider: 'openrouter',
        apiKeyEnv: 'OPENROUTER_API_KEY',
        icon: null,
        badge: 'Free',
        description: 'DeepSeek Chat V3 via OpenRouter with text understanding.',
        capabilities: ['text', 'code'],
        contextWindow: 64000,
        maxTokens: 4096,
        live: false,
        url: 'https://openrouter.ai/models/deepseek/deepseek-chat-v3-0324:free',
    },
    {
        id: 'openrouter/cypher-alpha:free',
        name: 'Cypher Alpha (OpenRouter)',
        provider: 'openrouter',
        apiKeyEnv: 'OPENROUTER_API_KEY',
        icon: null,
        badge: 'Free',
        description: 'Cypher Alpha via OpenRouter with text understanding.',
        capabilities: ['text', 'code'],
        contextWindow: 64000,
        maxTokens: 4096,
        live: false,
        url: 'https://openrouter.ai/models/openrouter/cypher-alpha:free',
    },
    {
        id: 'openrouter/horizon-alpha',
        name: 'Horizon Alpha (OpenRouter)',
        provider: 'openrouter',
        apiKeyEnv: 'OPENROUTER_API_KEY',
        icon: null,
        description: 'Horizon Alpha via OpenRouter with text understanding.',
        capabilities: ['text', 'code'],
        contextWindow: 256000,
        maxTokens: 128000,
        live: false,
        url: 'https://openrouter.ai/models/openrouter/horizon-alpha',
    },
];

export const OPENROUTER_PROVIDER_CONFIG = {
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api',
    keyLabel: 'OpenRouter API Key',
    envKeys: ['OPENROUTER_API_KEY'],
    signupUrl: 'https://openrouter.ai/keys',
};