// OpenAI Models Configuration
export const OPENAI_MODELS = [
    {
        id: 'gpt-4.1-2025-04-14',
        name: 'GPT-4.1',
        provider: 'openai',
        apiKeyEnv: 'OPENAI_API_KEY',
        icon: null,
        description: 'GPT-4.1 is OpenAI\'s most capable model with text and image understanding.',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 128000,
        maxTokens: 4096,
        live: false,
        url: 'https://openai.com/models/gpt-4.1-2025-04-14',
    },
    {
        id: 'o4-mini-2025-04-16',
        name: 'O4 Mini',
        provider: 'openai',
        apiKeyEnv: 'OPENAI_API_KEY',
        icon: null,
        description: 'O4 Mini is a faster, more efficient version of GPT-4 with text and image capabilities.',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 128000,
        maxTokens: 4096,
        live: false,
        url: 'https://openai.com/models/o4-mini-2025-04-16',
    },
    {
        id: 'o3-2025-04-16',
        name: 'O3',
        provider: 'openai',
        apiKeyEnv: 'OPENAI_API_KEY',
        icon: null,
        description: 'O3 is a faster, more efficient version of GPT-4 with text and image capabilities.',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 128000,
        maxTokens: 4096,
        live: false,
        url: 'https://openai.com/models/o3-2025-04-16',
    },
    {
        id: 'o3',
        name: 'O3',
        provider: 'openai',
        apiKeyEnv: 'OPENAI_API_KEY',
        icon: null,
        description: 'Latest OpenAI reasoning model',
        capabilities: ['text', 'code', 'reasoning'],
        contextWindow: 128000,
        maxTokens: 4096,
        live: false,
    },
    {
        id: 'gpt-4o',
        name: 'GPT-4o',
        provider: 'openai',
        apiKeyEnv: 'OPENAI_API_KEY',
        icon: null,
        description: 'OpenAI multimodal model',
        capabilities: ['text', 'vision', 'code'],
        contextWindow: 128000,
        maxTokens: 4096,
        live: false,
    },
];

export const OPENAI_PROVIDER_CONFIG = {
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com',
    keyLabel: 'OpenAI API Key',
    envKeys: ['OPENAI_API_KEY'],
    signupUrl: 'https://platform.openai.com/api-keys',
};